2025-09-10 07:49:00 - INFO - ###############################
2025-09-10 07:49:00 - INFO - TEST INFO LOGGING FINALLY
2025-09-10 07:49:00 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-10 07:49:00 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-10 07:49:00 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-10 07:49:00 - INFO - LOGGER STARTED
2025-09-10 07:49:00 - INFO - ###############################
2025-09-10 07:49:00 - INFO - Stated connect to db
2025-09-10 07:49:00 - INFO - Users db created/exist
2025-09-10 07:49:02 - INFO - Start schedule normalization
2025-09-10 07:49:02 - INFO - Schedule normalized
2025-09-10 07:53:15 - ERROR - Infinity polling: polling exited
2025-09-10 07:53:15 - ERROR - Break infinity polling
2025-09-10 07:53:15 - INFO - ###############################
2025-09-10 07:53:15 - INFO - TEST INFO LOGGING FINALLY
2025-09-10 07:53:15 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-10 07:53:15 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-10 07:53:15 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-10 07:53:15 - INFO - LOGGER STARTED
2025-09-10 07:53:15 - INFO - ###############################
2025-09-10 07:53:15 - INFO - Stated connect to db
2025-09-10 07:53:15 - INFO - Users db created/exist
2025-09-10 07:53:17 - INFO - Start schedule normalization
2025-09-10 07:53:17 - INFO - Schedule is the same. Cancel.
2025-09-10 08:15:36 - INFO - ###############################
2025-09-10 08:15:36 - INFO - TEST INFO LOGGING FINALLY
2025-09-10 08:15:36 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-10 08:15:36 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-10 08:15:36 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-10 08:15:36 - INFO - LOGGER STARTED
2025-09-10 08:15:36 - INFO - ###############################
2025-09-10 08:15:36 - INFO - Stated connect to db
2025-09-10 08:15:36 - INFO - Users db created/exist
2025-09-10 08:15:37 - INFO - Start schedule normalization
2025-09-10 08:15:37 - INFO - Schedule is the same. Cancel.
2025-09-10 08:15:39 - ERROR - Infinity polling: polling exited
2025-09-10 08:15:39 - ERROR - Break infinity polling
2025-09-10 08:16:01 - INFO - ###############################
2025-09-10 08:16:01 - INFO - TEST INFO LOGGING FINALLY
2025-09-10 08:16:01 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-10 08:16:01 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-10 08:16:01 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-10 08:16:01 - INFO - LOGGER STARTED
2025-09-10 08:16:01 - INFO - ###############################
2025-09-10 08:16:01 - INFO - Stated connect to db
2025-09-10 08:16:01 - INFO - Users db created/exist
2025-09-10 08:16:03 - INFO - Start schedule normalization
2025-09-10 08:16:03 - INFO - Schedule is the same. Cancel.
2025-09-10 08:16:14 - ERROR - Infinity polling exception: TeleBot.register_next_step_handler() missing 1 required positional argument: 'callback'
2025-09-10 08:16:14 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 9759, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\telegram_bot\main.py", line 119, in get_help_contact
    bot.register_next_step_handler(send_to_admin_helper_message)
TypeError: TeleBot.register_next_step_handler() missing 1 required positional argument: 'callback'

2025-09-10 08:20:44 - INFO - ###############################
2025-09-10 08:20:44 - INFO - TEST INFO LOGGING FINALLY
2025-09-10 08:20:44 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-10 08:20:44 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-10 08:20:44 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-10 08:20:44 - INFO - LOGGER STARTED
2025-09-10 08:20:44 - INFO - ###############################
2025-09-10 08:20:44 - INFO - Stated connect to db
2025-09-10 08:20:44 - INFO - Users db created/exist
2025-09-10 08:20:46 - INFO - Start schedule normalization
2025-09-10 08:20:46 - INFO - Schedule is the same. Cancel.
2025-09-10 08:25:47 - INFO - Start schedule normalization
2025-09-10 08:25:47 - INFO - Schedule is the same. Cancel.
